### ISSUE TITLE
isRTL Issue in react native

### ISSUE THREAD

**Issue by crzycoder** [Soomgo-Mobile/react-native-animated-pagination-dot#10]
Animated Dots not working when App is in RTL state.

**Comment by pratt3351** [comment]
can i see your issue in RTL state ?
are you just wanna horizontal dot list to vertical dot list ?

@crzycoder

**Comment by pratt3351** [comment]
i can't understand what you are talking about.
i try to I18nManager.forceRTL(true); in example app.
it seems like below screen shots.
![RTL_issue](https://user-images.githubusercontent.com/4319422/92296751-ae6e5d00-ef72-11ea-8d52-2279ce8c1f86.png)

you mean its not necessary reverse it ? @crzycoder
