### ISSUE TITLE
Only ship .js & .d.ts files when distributing via npm

### ISSUE THREAD

**Issue by ccheney** [Soomgo-Mobile/react-native-animated-pagination-dot#15]
> Right now, users who are trying to consume this library with TypeScript using settings like `noImplicitAny` are having a negative user experience because the packaged `.ts` files are getting fully re-checked. See [microsoft/TypeScript#15363](https://github.com/microsoft/TypeScript/issues/15363) for an example of a problem caused by this.
> 
> Running TypeScript with `--declaration` to produce `.d.ts` files and adding your regular `.ts` files to an `.npmignore` file will prevent this issue.

**Comment by pratt3351** [comment]
okay i will fix it .! 
sorry for late answer!
