### ISSUE TITLE
Error build for Android

### ISSUE THREAD

**Issue by aspidvip** [Soomgo-Mobile/react-native-animated-pagination-dot#16]
react-native: 0.61.5
 "react-native-animated-pagination-dot": 0.1.8

`  error SyntaxError: /var/app/XXXXX/build-20201016081531/node_modules/react-native-animated-pagination-dot/src/util/DotUtils.ts: Unexpected token, expected ";" (39:73)
15:17:28
  
15:17:28
    37 | }
15:17:28
    38 |
15:17:28
  > 39 | export const getDotStyle = ({ idx, curPage, maxPage }:getDotStylePayload):IDotStyle => {
15:17:28
       |                                                                          ^
15:17:28
    40 |     let type = EnumDotType.SMALL;
15:17:28
    41 |
15:17:28
    42 |     if (maxPage < 5) {. Run CLI with --verbose flag for more details.
15:17:28
  
15:17:28
  > Task :app:bundleReleaseJsAndAssets FAILED
15:17:29

  `

**Comment by aspidvip** [comment]
`  error SyntaxError: /var/app/tvil.ru.android.guest/build-20201016081531/node_modules/react-native-animated-pagination-dot/src/util/DotUtils.ts: Unexpected token, expected ";" (39:73)
15:17:28
  
15:17:28
    37 | }
15:17:28
    38 |
15:17:28
  > 39 | export const getDotStyle = ({ idx, curPage, maxPage }:getDotStylePayload):IDotStyle => {
                                                                                                                                            ^
15:17:28
       |                                                                          ^
15:17:28
    40 |     let type = EnumDotType.SMALL;
15:17:28
    41 |
15:17:28
    42 |     if (maxPage < 5) {. Run CLI with --verbose flag for more details.
15:17:28
  
15:17:28
  > Task :app:bundleReleaseJsAndAssets FAILED
15:17:29
  ReactNativeFirebase WARNING: NPM package '@react-native-firebase/messaging' depends on '@react-native-firebase/app' v8.4.2 but found v8.4.3, this might cause build issues or runtime crashes.
15:17:29
  `

**Comment by pratt3351** [comment]
sorry for late answer .!
try it again please? @aspidvip
