### ISSUE TITLE
Custom empty dot color

### ISSUE THREAD

**Issue by murilopf-up** [Soomgo-Mobile/react-native-animated-pagination-dot#51]
have you any plans to add a possibility to change empty dot color? 
today with fixed opacity at the dots in some screens is hard to see the dot that is not selected.

<img width="248" alt="Captura de Tela 2022-09-06 às 08 35 24" src="https://user-images.githubusercontent.com/109311014/188626202-5f241c42-9e90-452a-87b6-8b3f57a56318.png">

**Comment by pratt3351** [comment]
you need just transparent dot color ? @murilopf-up

**Comment by murilopf-up** [comment]
Yeah, it would be nice if we can control the opacity or background color of EmptyDot.
I can try to send a PR if you are busy

**Comment by pratt3351** [comment]
yeah i understand that what you want
it's not a big stuff. so i can do it.

@murilopf-up

**Comment by pratt3351** [comment]
is this what you want ? 

![ezgif-5-eb3192f891](https://user-images.githubusercontent.com/4319422/189922878-7172d48c-8307-47ac-806a-6255f7bd6d3b.gif)

i'll publish new version to npm.

if not, give me some feedback. and i'll handle it
@murilopf-up

**Comment by murilopf-up** [comment]
Yeah, that's it!
I will be able to change the opacity and background color?

**Comment by pratt3351** [comment]
if i publish it, you can handle only background color.
opacity is control by fixed animated value.

you also want to use opacity value.?
i think it's not necessary.
@murilopf-up

**Comment by murilopf-up** [comment]
I think it's not necessary, you are right!
I asked just to confirmm thanks @pratt3351

**Comment by pratt3351** [comment]
i publish it on npm !
you can use it on v.0.4.0
enjoy!
@murilopf-up
