### ISSUE TITLE
Cant change dot size

### ISSUE THREAD

**Issue by pratt3351** [Soomgo-Mobile/react-native-animated-pagination-dot#6]
cant change dot Size.

**Comment by pratt3351** [comment]
Not necessory to this library

**Comment by Derewith** [comment]
Can you please help me transforming the dots into bars? 
I've done some changes like removing borderRadius but, if i try to increment the DotStyle.size and adding containerWidth to full card width, the whole component broke.

Can you help?

**Comment by pratt3351** [comment]
@Derewith 
You wanna change size change ?  i will updated it until this month !

**Comment by Derewith** [comment]
@rouge3351 yeah, i think it will be awesome! Thanks again

**Comment by pratt3351** [comment]
Hi i'm finally make your suggettion
I define in props `sizeRatio`. you can use that when you wanna change size.

but i recommend you to sizeRatio between 1 to 2
it is necessary prevent ui broken issues
total container size dependent on each dot size
so i will recommend you to use this props option between 1 to 2

i hope use this props ! thanks !

@Derewith 
![Aug-29-2020 19-28-31](https://user-images.githubusercontent.com/4319422/91634767-df5c0880-ea2d-11ea-90f6-ae7bb4030325.gif)

**Comment by pratt3351** [comment]
publish 0.1.7 npm module! enjoy!

**Comment by felire** [comment]
Probably you will find this library more useful and more configurable:
[https://github.com/felire/react-native-animated-dots-carousel](https://github.com/felire/react-native-animated-dots-carousel)

@Derewith @pratt3351
